server:
  port: 8083

spring:
  application:
    name: ai-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  exchange:
    news: news.exchange
  queue:
    conversation: conversation.queue
  routing-key:
    conversation: conversation.save

logging:
  level:
    com.thet0rnado.mylittleagentworld.ai: DEBUG